#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer
CONFIG="
frontend myfrontend
    bind *:80
    mode http
    default_backend web_servers
backend web_servers
   balance roundrobin
   server 240202-web-01 52.207.208.207:80 check
   server 240202-web-02 100.26.57.232:80 check
"
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
# Backup original config file before attempt modifications
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
printf "%s" "$CONFIG" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
