#!/usr/bin/env bash

# Name of the private key
# Number of bits for the key
# Passphrase for the key
# Generate the RSA key pair
private_key="school"

bits=4096
passphrase="betty"

ssh-keygen -t rsa -b $bits -N $passphrase -f $private_key

echo "RSA key pair generated."

